#!/bin/sh

sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

sudo . ~/.nvm/nvm.sh

sudo nvm install v10.11.0

sudo npm install

sudo nodemon index.js

exit

EOF
